# installs Docker, Docker Compose, Anchore Engine, and Jenkins on the EC2 instance

---
- name: install
  connection: ssh
  hosts: "{{ hostvars['localhost']['var_one'] }}"
  become: True
  tasks:
  # Docker
  - name: Update the apt package index
    apt:
      update_cache: yes
  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  - name: Add Docker's official GPG key
    shell: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -"
  - name: Setup the stable repository ubuntu bionic
    apt_repository:
      repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable'
  - name: Update the apt package index
    apt:
      update_cache: yes
  - name: Install Docker Engine
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io 
  # Docker Compose
  - name: Install Docker Compose
    apt:
      pkg:
      - docker-compose
  # Anchore Engine
  - name: Download the docker-compose.yaml
    shell: "curl https://docs.anchore.com/current/docs/engine/quickstart/docker-compose.yaml > docker-compose.yaml"
  - name: Start Anchore Engine
    shell: "docker-compose up -d"
  # Jenkins
  - name: Pull jenkinsci/blueocean
    shell: "sudo docker run -u root -d --name jenkins -p 8080:8080 -p 50000:50000 -v /var/run/docker.sock:/var/run/docker.sock -v jenkins-data:/var/jenkins_home jenkinsci/blueocean"